config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :vaccinations, only: [:index] do
    collection {
      post :import
      delete :destroy
    }
  end
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  included do
    scope :filter_by_country, lambda { |country_ids|
      where country_id: country_ids.split(",")
    }
    scope :filter_by_data_source, lambda { |data_source|
      where data_source: data_source
    }
    scope :filter_by_date_updated_start_date, lambda { |date_updated_start_date|
      where "date_updated >= ?", date_updated_start_date
    }
    scope :filter_by_date_updated_end_date, lambda { |date_updated_end_date|
      where "date_updated <= ?", date_updated_end_date
    }
    scope :filter_by_first_vaccine_date_start, lambda { |first_vaccine_date_start|
      where "first_vaccine_date >= ?", first_vaccine_date_start
    }
    scope :filter_by_first_vaccine_date_end, lambda { |first_vaccine_date_end|
      where "first_vaccine_date <= ?", first_vaccine_date_end
    }
    scope :filter_by_vaccine, lambda { |vaccine_ids|
      where("EXISTS (:vaccination_details)",
            vaccination_details: VaccinationDetail.select("1")
              .where("vaccination_details.vaccination_id = vaccinations.id")
              .where(vaccine_id: vaccine_ids.split(",")))
    }
  end

  module ClassMethods
    def filter(filtering_params)
      results = where(nil) # create an anonymous scope
      filtering_params.each do |key, value|
        results = results.public_send("filter_by_#{key}", value) if value.present?
      end
      results
    end
  end
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :vaccinations, dependent: :destroy

  validates :country, :iso2, :iso3, presence: true
end

app/models/csv_vaccination.rb
class CsvVaccination < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :rememberable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :validatable
  validates :country_id, presence: true
end

app/models/vaccination.rb
class Vaccination < ApplicationRecord
  include Filterable

  has_many :vaccination_details, dependent: :destroy
  has_many :vaccines, through: :vaccination_details
  belongs_to :country

  # enable nested attributes
  accepts_nested_attributes_for :vaccination_details

  enum data_source: {
    reporting: 0,
    owid:      1
  }, _prefix: true
end

app/models/vaccination_detail.rb
class VaccinationDetail < ApplicationRecord
  belongs_to :vaccination
  belongs_to :vaccine
end

app/models/vaccine.rb
class Vaccine < ApplicationRecord
  has_many :vaccine_details, dependent: :destroy
  has_many :vaccination_details, dependent: :destroy
  has_many :vaccinations, through: :vaccination_details

  validates :vaccine_name, presence: true
end

app/models/vaccine_detail.rb
class VaccineDetail < ApplicationRecord
  belongs_to :vaccine
  belongs_to :country
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_country_paramaters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :country_id, :password, :password_confirmation, :is_admin)
    end
  end

  def configure_country_paramaters
    @countries = Country.all
    @default_user_country = Country.find_by(iso2: "PH")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to vaccinations_path if redirect_referer.include? request.referer
  end

  private

  def redirect_referer
    [
      "http://localhost:3000/users/sign_up",
      "http://localhost:3000/users/sign_in",
      "https://nante-covid-data.herokuapp.com/users/sign_up",
      "https://nante-covid-data.herokuapp.com/users/sign_in",
      "http://nante-covid-data.herokuapp.com/users/sign_up",
      "http://nante-covid-data.herokuapp.com/users/sign_in"
    ]
  end
end

app/controllers/vaccinations_controller.rb
class VaccinationsController < ApplicationController
  before_action :authenticate_user!
  before_action :no_file_chosen, only: %i[import]

  def index
    @vaccinations = Vaccination.filter(filtering_params)
                               .includes(:vaccines, :country)

    @chart_data = @vaccinations.order("sum_total_vaccinations desc")
                               .group(:vaccine_name)
                               .sum(:total_vaccinations)

    @countries = Country.all
    @vaccines = Vaccine.all.order(:vaccine_name)
  end

  def import
    file_content = params[:file].read.force_encoding("UTF-8")

    AddVaccinationWorker.perform_async(file_content)
    flash[:notice] = "CSV data has been successfully saved."
    redirect_to root_path
  end

  def destroy
    RemoveVaccinationWorker.perform_async
    flash[:notice] = "CSV data has been successfully deleted."
    redirect_to root_path
  end

  private

  def no_file_chosen
    return unless params[:file].nil?

    flash[:alert] = "You must choose a file to import!"
    redirect_to vaccinations_path
  end

  # A list of the param names that can be used for filtering the vaccinations list
  def filtering_params
    params.slice(:country, :data_source, :vaccine,
                 :date_updated_start_date, :date_updated_end_date,
                 :first_vaccine_date_start, :first_vaccine_date_end)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/views/home/index.html.erb
<h4 class="ui header">Home</h4>
<p>COVID VACCINATION DATA CSV UPLOAD</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>COVID VACCINATION DATA CSV UPLOAD</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.rawgit.com/mdehoog/Semantic-UI/6e6d051d47b598ebab05857545f242caf2b4b48c/dist/semantic.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://cdn.rawgit.com/mdehoog/Semantic-UI/6e6d051d47b598ebab05857545f242caf2b4b48c/dist/semantic.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>

  <body>
    <div class="ui container">
      <%= render "shared/navbar" %>
    </div>

    <div class="ui container">
      <%= render "shared/error_message" %>

      <div class="ui row"></div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if notice.present? %>
  <div class="ui message green">
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert.present? %>
  <div class="ui message red">
    <p><%= alert %></p>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="ui inverted menu">
  <%= link_to "Home", root_path, class: "#{active?(root_path)} item" %>
  <% if !user_signed_in? %>
    <%= link_to "Login", new_user_session_path, class: "#{active?(new_user_session_path)} item" %>
    <%= link_to "Register", new_user_registration_path, class: "#{active?(new_user_registration_path)} item" %>
  <% else %>
    <%= link_to "Dashboard", vaccinations_path, class: "#{active?(vaccinations_path)} item" %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
  <% end %>
</div>

app/views/vaccinations/_filter.html.erb
<%= form_tag vaccinations_path, multipart: true, class: 'ui form', method: 'get' do %>
  <div class="ui form">
    <div class="four fields">
      <div class="field">
        <label>Date Updated (Date Range)</label>
        <div class="ui calendar" id="date_updated_start_date">
          <div class="ui input left icon">
            <i class="calendar icon"></i>
            <input type="text" name="date_updated_start_date" value="<%= params[:date_updated_start_date] %>" placeholder="Start Date">
          </div>
        </div>
      </div>

      <div class="field">
        <label>&nbsp;</label>
        <div class="ui calendar" id="date_updated_end_date">
          <div class="ui input left icon">
            <i class="calendar icon"></i>
            <input type="text" name="date_updated_end_date" value="<%= params[:date_updated_end_date] %>" placeholder="End Date">
          </div>
        </div>
      </div>

      <div class="field">
        <label>First Vaccine (Date Range)</label>
        <div class="ui calendar" id="first_vaccine_date_start">
          <div class="ui input left icon">
            <i class="calendar icon"></i>
            <input type="text" name="first_vaccine_date_start" value="<%= params[:first_vaccine_date_start] %>" placeholder="Start Date">
          </div>
        </div>
      </div>

      <div class="field">
        <label>&nbsp;</label>
        <div class="ui calendar" id="first_vaccine_date_end">
          <div class="ui input left icon">
            <i class="calendar icon"></i>
            <input type="text" name="first_vaccine_date_end" value="<%= params[:first_vaccine_date_end] %>" placeholder="End Date">
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="ui form">
    <div class="two fields">
      <div class="field">
        <div class="ui multiple search selection dropdown">
          <input type="hidden" name="country" value="<%= params[:country] %>">
          <i class="dropdown icon"></i>
          <div class="default text">Country</div>
          <div class="menu">
            <% countryObj.each do |country| %>
              <div class="item" data-value="<%= country.id %>">
                <i class="<%= !country.iso2.nil? ? country.iso2.downcase : country.iso3.first(2).downcase %> flag"></i><%= country.country %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="ui multiple search selection dropdown">
          <input type="hidden" name="vaccine" value="<%= params[:vaccine] %>">
          <i class="dropdown icon"></i>
          <div class="default text">Vaccines Used</div>
          <div class="menu">
            <% vaccineObj.each do |vaccine| %>
              <div class="item" data-value="<%= vaccine.id %>"><%= vaccine.vaccine_name %></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="ui form">
    <div class="four fields">
      <div class="field">
        <div class="ui selection dropdown">
          <input type="hidden" name="data_source" value="<%= params[:data_source] %>">
          <i class="dropdown icon"></i>
          <div class="default text">Data Source</div>
          <div class="menu">
            <div class="item" data-value="0">REPORTING</div>
            <div class="item" data-value="1">OWID</div>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="ui left icon input">
          <%= submit_tag "Search", name: nil, class: "ui submit button primary" %>
          <i class="search icon"></i>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/vaccinations/_form.html.erb
<h5 class="ui header">
  Upload CSV Data
</h5>

<%= form_tag import_vaccinations_path, multipart: true, class: 'ui form' do %>
  <div class="field">
    <%= file_field_tag :file %>
  </div>

  <div class="ui left icon input">
    <%= submit_tag "Import CSV", class: "ui submit button primary " %>
    <i class="upload icon"></i>
  </div>

  <%= link_to "Delete All", vaccinations_path, method: :delete, class: 'ui red button' %>
<% end %>

app/views/vaccinations/index.html.erb
<h4 class="ui header">WHO Coronavirus (COVID-19) Dashboard</h4>

<% if current_user.is_admin? %>
  <%= render "form" %>
  <div class="ui divider"></div>
<% end %>

<div class="ui grid">
  <div class="sixteen wide column">
    <div class="ui segment">
      <%= render "filter", countryObj: @countries, vaccineObj: @vaccines %>
    </div>
  </div>
</div>

<% if @chart_data.length > 0 %>
  <h3>Total Vaccinations Per Vaccine</h3>
  <div class="ui grid">
    <div class="sixteen wide column">
      <div class="ui segment">
        <%= bar_chart @chart_data, xtitle: "Total Vaccinations", ytitle: "Vaccines" %>
      </div>
    </div>
  </div>
<% end %>

<table class="ui striped table">
  <thead>
    <tr>
      <th>#</th>
      <th>Country</th>
      <th>ISO3</th>
      <th>Data Source</th>
      <th>Date Updated</th>
      <th class="right aligned">Total Vaccinations</th>
      <th class="right aligned">Persons Vaccinated 1Plus Dose</th>
      <th class="right aligned">Total Vaccinations Per 100</th>
      <th>Vaccines Used</th>
      <th>First Vaccine Date</th>
      <th class="center aligned">Number of Vaccine Type Used</th>
    </tr>
  </thead>
  <tbody>
    <% @vaccinations.each_with_index do |data, index| %>
      <tr>
        <td data-label="No"><%= index + 1 %></td>
        <td data-label="Country"><%= data.country.try(&:country) %></td>
        <td data-label="ISO3"><%= data.country.try(&:iso3) %></td>
        <td data-label="Data Source"><%= data.data_source.upcase %></td>
        <td data-label="Date Updated"><%= data.date_updated %></td>
        <td data-label="Total Vaccinations" class="right aligned"><%= number_with_delimiter(data.total_vaccinations) %></td>
        <td data-label="Persons Vaccinated 1Plus Dose" class="right aligned"><%= number_with_delimiter(data.persons_vaccinated_1plus_dose) %></td>
        <td data-label="Total Vaccinations Per 100" class="right aligned"><%= number_with_delimiter(data.total_vaccinations_per100) %></td>
        <td data-label="Vaccines Used">
          <%= data.vaccines.map{ |vaccine| vaccine.vaccine_name }.join(", ") %>
        </td>
        <td data-label="First Vaccine Date"><%= data.first_vaccine_date %></td>
        <td data-label="Number of Vaccine Type Used" class="center aligned"><%= data.vaccination_details.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  $(document).ready(function() {
    $('.ui.dropdown').dropdown({
      "clearable": true
    });

    $('#date_updated_start_date').calendar({
      type: 'date',
      endCalendar: $('#date_updated_end_date'),
      formatter: {
        date: function (date, settings) {
          if (!date) return '';
          var day = date.getDate();
          var month = date.getMonth() + 1;
          var year = date.getFullYear();
          return year + '-' + String("00" + month).slice(-2) + '-' + String("00" + day).slice(-2);
        }
      }
    });

    $('#date_updated_end_date').calendar({
      type: 'date',
      startCalendar: $('#date_updated_start_date'),
      formatter: {
        date: function (date, settings) {
          if (!date) return '';
          var day = date.getDate();
          var month = date.getMonth() + 1;
          var year = date.getFullYear();
          return year + '-' + String("00" + month).slice(-2) + '-' + String("00" + day).slice(-2);
        }
      }
    });

    $('#first_vaccine_date_start').calendar({
      type: 'date',
      endCalendar: $('#first_vaccine_date_end'),
      formatter: {
        date: function (date, settings) {
          if (!date) return '';
          var day = date.getDate();
          var month = date.getMonth() + 1;
          var year = date.getFullYear();
          return year + '-' + String("00" + month).slice(-2) + '-' + String("00" + day).slice(-2);
        }
      }
    });

    $('#first_vaccine_date_end').calendar({
      type: 'date',
      startCalendar: $('#first_vaccine_date_start'),
      formatter: {
        date: function (date, settings) {
          if (!date) return '';
          var day = date.getDate();
          var month = date.getMonth() + 1;
          var year = date.getFullYear();
          return year + '-' + String("00" + month).slice(-2) + '-' + String("00" + day).slice(-2);
        }
      }
    });
  });
</script>